# Generated by Django 4.2 on 2023-04-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=200)),
                ('descripcion_libro', models.TextField()),
                ('updated_libro', models.DateTimeField(auto_now=True)),
                ('created_libro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
