# Generated by Django 4.2 on 2023-05-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_autor_autor_libro_genero_genero_libro_libro_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='libros'),
        ),
    ]
