# Generated by Django 4.2 on 2023-05-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_libro_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='archivo',
        ),
    ]
