# Generated by Django 4.2 on 2023-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_libro_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='ruta',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
